//API
export const API = 'API';

//UI ACTIONS
export const ON_SEARCH = 'ON_SEARCH';
export const ON_CLEAR_SEARCH = 'ON_CLEAR_SEARCH';
export const TAB_NEW_INDEX = 'TAB_NEW_INDEX';

//UI INDICATORS
export const START_NETWORK = 'START_NETWORK';
export const END_NETWORK = 'END_NETWORK';
export const SHOW_LOAD_MORE = 'SHOW_LOAD_MORE';
export const HIDE_LOAD_MORE = 'HIDE_LOAD_MORE';

//ERRORS
export const SHOW_GENERIC_ERROR = 'GENERIC_ERROR';
export const HIDE_GENERIC_ERROR = 'HIDE_GENERIC_ERROR';
export const SHOW_NETWORK_ERROR = 'SHOW_NETWORK_ERROR';
export const HIDE_NETWORK_ERROR = 'HIDE_NETWORK_ERROR';


//PHOTOS
export const LOAD_MORE_PHOTOS = 'LOAD_MORE_PHOTOS';
export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_MORE_PHOTOS = 'SET_MORE_PHOTOS';
export const INCREMENT_PHOTOS_PAGE = 'INCREMENT_PHOTOS_PAGE';
export const RESET_PHOTOS_PAGE = 'RESET_PHOTOS_PAGE';

//GROUPS
export const SET_GROUPS = 'SET_GROUPS';
export const SET_MORE_GROUPS = 'SET_MORE_GROUPS';
export const LOAD_MORE_GROUPS = 'LOAD_MORE_GROUPS';
export const INCREMENT_GROUPS_PAGE = 'INCREMENT_GROUPS_PAGE';
export const RESET_GROUPS_PAGE = 'RESET_GROUPS_PAGE';

//LIFECYCLE
export const PAGE_MOUNTED = 'PAGE_MOUNTED';
