

export const API = 'API';
export const START_NETWORK = 'START_NETWORK';
export const END_NETWORK = 'END_NETWORK';


export const SHOW_GENERIC_ERROR = 'GENERIC_ERROR';
export const HIDE_GENERIC_ERROR = 'HIDE_GENERIC_ERROR';
export const SHOW_NETWORK_ERROR = 'NETWORK_ERROR';
export const HIDE_NETWORK_ERROR = 'HIDE_NETWORK_ERROR';
